<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-IVL2HKTT" failures="0" tests="6" name="ebanking.testcases.TC_LoginDDT_1101" time="4.836" errors="1" timestamp="2024-01-06T18:44:54 GMT+01:00" skipped="5">
  <testcase classname="ebanking.testcases.TC_LoginDDT_1101" name="LoginDDT" time="0.000">
    <skipped/>
  </testcase> <!-- LoginDDT -->
  <testcase classname="ebanking.testcases.TC_LoginDDT_1101" name="LoginDDT" time="0.000">
    <skipped/>
  </testcase> <!-- LoginDDT -->
  <testcase classname="ebanking.testcases.TC_LoginDDT_1101" name="LoginDDT" time="0.000">
    <skipped/>
  </testcase> <!-- LoginDDT -->
  <testcase classname="ebanking.testcases.TC_LoginDDT_1101" name="setup" time="4.836">
    <error message="current thread is not owner" type="java.lang.IllegalMonitorStateException">
      <![CDATA[java.lang.IllegalMonitorStateException: current thread is not owner
at java.base/java.lang.Object.wait0(Native Method)
at java.base/java.lang.Object.wait(Object.java:366)
at ebanking.testcases.Baseclass.setup(Baseclass.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- setup -->
  <testcase classname="ebanking.testcases.TC_LoginDDT_1101" name="LoginDDT" time="0.000">
    <skipped/>
  </testcase> <!-- LoginDDT -->
  <testcase classname="ebanking.testcases.TC_LoginDDT_1101" name="LoginDDT" time="0.000">
    <skipped/>
  </testcase> <!-- LoginDDT -->
</testsuite> <!-- ebanking.testcases.TC_LoginDDT_1101 -->
